<?php

function choices_menu()
{

    $items['results'] = array(
        'title' => 'Your Intership!',
        'page callback' => 'get_result',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}


function get_result()
{
    $array_students = array(
        'Erica' => array(
            'first' => 'FlowerPot',
            'second' => 'Vacasa',
            'third' => 'Dart'
        ),
        'David' => array(
            'first' => 'MetalToad',
            'second' => 'Lumen',
            'third' => 'Whitman'
        ),
        'Bojana' => array(
            'first' => 'Drupal',
            'second' => 'Lumen',
            'third' => 'Graybox'
        ),
        'Nhu' => array(
            'first' => 'Phase2',
            'second' => 'Whitman',
            'third' => 'empty'
        ),
        'James' => array(
            'first' => 'Dart',
            'second' => 'Lumen',
            'third' => 'Flowerpot'
        ),
        'Jill' => array(
            'first' => 'Emerge',
            'second' => 'Phase2',
            'third' => 'Lumen'
        ),
        'Liz' => array(
            'first' => 'Vacasa',
            'second' => 'Lumen',
            'third' => 'Drupal'
        ),
        'Tom' => array(
            'first' => 'Phase2',
            'second' => 'Copious',
            'third' => 'Graybox'
        ),
        'Kenna' => array(
            'first' => 'Phase2',
            'second' => 'Drupal',
            'third' => 'Intel'
        ),
        'Cynthia' => array(
            'first' => 'Intel',
            'second' => 'Phase2',
            'third' => 'Drupal'
        ),
        'Brian' => array(
            'first' => 'Emerge',
            'second' => 'Vacasa',
            'third' => 'Lumen'
        ),
        'Patrick' => array(
            'first' => 'Phase2',
            'second' => 'FlowerPot',
            'third' => 'empty'
        ),
        'Tanner' => array(
            'first' => 'Copious',
            'second' => 'Tanner',
            'third' => 'empty'
        ),
        'Brett' => array(
            'first' => 'Copious',
            'second' => 'Graybox',
            'third' => 'Whitman'
        ),
        'KyleGC' => array(
            'first' => 'Phase2',
            'second' => 'MetalToad',
            'third' => 'Graybox'
        ),
        'KyleB' => array(
            'first' => 'Copious',
            'second' => 'Graybox',
            'third' => 'Flowerpot'
        ),
        'Conor' => array(
            'first' => 'Phase2',
            'second' => 'Intel',
            'third' => 'Whitman'
        ),
        'Connor' => array(
            'first' => 'Phase2',
            'second' => 'Copious',
            'third' => 'MetalToad'
        ),
        'Geoff' => array(
            'first' => 'Phase2',
            'second' => 'Vacasa',
            'third' => 'Dart'
        ),
        'Bryan' => array(
            'first' => 'MetalToad',
            'second' => 'Whitman',
            'third' => 'Lumen'
        ),
        'Reid' => array(
            'first' => 'Intel',
            'second' => 'Emerge',
            'third' => 'Drupal'
        ),
        'Tommy' => array(
            'first' => 'Intel',
            'second' => 'FlowerPot',
            'third' => 'Dart'
        ),
        'Jon' => array(
            'first' => 'Vacasa',
            'second' => 'Drupal',
            'third' => 'MetalToad'
        ),
        'Chitra' => array(
            'first' => 'Phase2',
            'second' => 'Whitman',
            'third' => 'Dart'
        ),
        'Evan' => array(
            'first' => 'Dart',
            'second' => 'Intel',
            'third' => 'Whitman'
        ),
        'Daniel' => array(
            'first' => 'Intel',
            'second' => 'Drupal',
            'third' => 'empty'
        ),
        'Abeer' => array(
            'first' => 'Vacasa',
            'second' => 'Copious',
            'third' => 'Graybox'
        ),
        'Kelly' => array(
            'first' => 'Emerge',
            'second' => 'Vacasa',
            'third' => 'Lumen'
        ),
        'Virginie' => array(
            'first' => 'FlowerPot',
            'second' => 'MetalToad',
            'third' => 'empty'
        )
    );
    $companies      = array(
        'Phase2' => -4,
        'Emerge' => 0,
        'Copious' => 0,
        'MetalToad' => 0,
        'FlowerPot' => 0,
        'Intel' => 0,
        'Drupal' => 0,
        'Vacasa' => 0,
        'Dart' => 0,
        'Lumen' => 0,
        'Whitman' => 0,
        'Graybox' => 0
    );
    $output         = '';

    foreach ($array_students as $student => $value) {
        foreach ($companies as $company_name => $intern_number) {
            if ($intern_number < 2) {

                if ($company_name == $value['first']) {
                    $value['company'] = $company_name;
                    $companies[$company_name] += 1;
                    continue;

                } elseif ($company_name == $value['second']) {
                    $value['company'] = $company_name;
                    $companies[$company_name] += 1;
                    continue;

                }
                elseif ($company_name == $value['third']) {
                    $value['company'] = $company_name;
                    $companies[$company_name] += 1;
                    continue;

                } else {
                    continue;
                }
            }
            //
            //
            // else {
            //     unset($companies[$company_name]);
            // }

        }

        $output .= '<br/><strong>Name:</strong> ' . $student . '<br/> <strong>First Choice </strong>: ' . $value['first'] . ' <br/> <strong>Second Choice </strong>: ' . $value['second'] . '<br/>' . 'Company: ' . $value['company'];

    }


    return $output;

}
