<?php

function choices_menu() {
        $items['choices'] = array(
        'title' => 'Choices!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('choices_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['results'] = array(
    'title' => 'Your Intership!',
    'page callback' => 'get_result',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
);
    return $items;
}
function choices_form() {
    $form['student_name'] = array(
        '#title' => 'Student Name',
        '#type' => 'textfield',
        '#description' => t("Please enter your first name.TitleCase it !"),
        '#element_validate' => array('element_check_student'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Find out your placement!',
    );
    return $form;
}

function choices_form_submit($form, &$form_state) {

    $student_name = $form_state['values']['student_name'];
    $_SESSION['student_name'] =$student_name;
    $_SESSION['all_students'] = array(
        'Erica' => array('first' => 'FlowerPot', 'second' => 'Vacasa'),
        'David' => array('first' => 'MetalToad', 'second' => 'Lumen'),
        'Bojana' => array('first' => 'Drupal', 'second' => 'Lumen'),
        'Nhu' => array('first' => 'Phase2', 'second' => 'Whitman'),
        'James' => array('first' => 'Dart', 'second' => 'Lumen'),
        'Jill'=> array('first' => 'Emerge', 'second' => 'Phase2'),
        'Liz'=> array('first' => 'Vacasa', 'second' => 'Lumen'),
        'Tom'=> array('first' => 'Phase2', 'second' => 'Copious'),
        'Kenna'=> array('first' => 'Phase2', 'second' => 'Drupal'),
        'Cynthia'=> array('first' => 'Intel', 'second' => 'Phase2'),
        'Brian'=> array('first' => 'Emerge', 'second' => 'Vacasa'),
        'Patrick'=> array('first' => 'Phase2', 'second' => 'FlowerPot'),
        'Tanner'=> array('first' => 'Copious', 'second' => 'Tanner'),
        'Brett'=> array('first' => 'Copious', 'second' => 'Graybox'),
        'KyleGC'=> array('first' => 'Phase2', 'second' => 'MetalToad'),
        'KyleB'=> array('first' => 'Copious', 'second' => 'Graybox'),
        'Conor'=> array('first' => 'Phase2', 'second' => 'Intel'),
        'Connor'=> array('first' => 'Phase2', 'second' => 'Copious'),
        'Geoff'=> array('first' => 'Phase2', 'second' => 'Vacasa'),
        'Bryan'=> array('first' => 'MetalToad', 'second' => 'Whitman'),
        'Reid'=> array('first' => 'Intel', 'second' => 'Emerge'),
        'Tommy'=> array('first' => 'Intel', 'second' => 'FlowerPot'),
        'Jon'=> array('first' => 'Vacasa', 'second' => 'Drupal'),
        'Chitra'=> array('first' => 'Phase2', 'second' => 'Whitman'),
        'Evan'=> array('first' => 'Dart', 'second' => 'Intel'),
        'Daniel'=> array('first' => 'Intel', 'second' => 'Drupal'),
        'Tom'=> array('first' => 'Phase2', 'second' => 'Copious'),
        'Abeer'=> array('first' => 'Vacasa', 'second' => 'Copious'),
        'Kelly'=> array('first' => 'Emerge', 'second' => 'Vacasa'),
        'Virginie'=> array('first' => 'FlowerPot', 'second' => 'MetalToad'),
    );

    $form_state['redirect']='results';

}

function element_check_student($element){
    if(!array_key_exists($element['#value'],$_SESSION['all_students']  )){
        form_error($element, t('That person is not in the class!!!!! Be real!'));
    }
}

function select_companies(){
    $companies= array (
        'Phase2' => 0,
        'Emerge' => 0,
        'Copious' => 0,
        'MetalToad' => 0,
        'FlowerPot' => 0,
        'Intel' => 0,
        'Drupal' => 0,
        'Vacasa' => 0,
        'Dart' => 0,
        'Lumen' => 0,
        'Whitman' => 0,
        'Graybox' => 0,
    );



}
function get_result(){
 $first_choice= $_SESSION['all_students'][$_SESSION['student_name']]['first'];
 $second_choice= $_SESSION['all_students'][$_SESSION['student_name']]['second'];

   $output = 'Hello ' . $_SESSION['student_name'] . '! <br/>Your Choices were: ' . $first_choice . ' & ' . $second_choice . ".";
   return $output;

}
